package orderApp.components.mainMenu.mainMenuComponents;

import orderApp.Main;
import orderApp.data.FileRWproduct;
public class AddProduct extends javax.swing.JFrame {
    
    private boolean productCodeIsCom = false;
    
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        productNameText = new javax.swing.JTextField();
        productCodeDisplay = new javax.swing.JLabel();
        confirmAddButton = new javax.swing.JButton();
        productQuantity = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(259, 254));
        setPreferredSize(new java.awt.Dimension(259, 254));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Product  Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        jLabel2.setText("Quantity");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 30));

        jLabel3.setText("Product Code");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 30));

        productNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productNameTextKeyReleased(evt);
            }
        });
        getContentPane().add(productNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 90, 30));

        productCodeDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(productCodeDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 90, 30));

        confirmAddButton.setText("ADD");
        confirmAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmAddButtonMouseClicked(evt);
            }
        });
        getContentPane().add(confirmAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        productQuantity.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(productQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productNameTextKeyReleased
        String temp = productNameText.getText();
        String firstFourLetters = "";
        
        if (temp.length() >= 4) {
            firstFourLetters = temp.substring(0, 4);
        } 
        
        String num = "";
        if(firstFourLetters.length() == 4){
            num = getUniqueNum();
            productCodeIsCom = true;
        }
        
        productCodeDisplay.setText(firstFourLetters.toUpperCase() + num);
    }//GEN-LAST:event_productNameTextKeyReleased

    private void confirmAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmAddButtonMouseClicked

        boolean quantity = checkQuantity();
      if(productCodeIsCom && quantity){
        
          for(int i = 0; i < Main.MAX_PRODUCTS; i++){
              
              if(Main.END_LINE.equals(Main.product[i].getProductCode())){
                  Main.product[i].setProductCode(productCodeDisplay.getText());
                  Main.product[i].setProductName(productNameText.getText());
                  Main.product[i].setProductQuantity(Integer.parseInt(productQuantity.getText()));
                  
                  Main.product[i + 1].setProductCode(Main.END_LINE);
                  FileRWproduct.fileWrite();
                  break;
              }
              
              
              
              
          }
          
          Main.addProductForm();
      }
        
        
    }//GEN-LAST:event_confirmAddButtonMouseClicked
    
    public String getUniqueNum(){
       
        String num = "";
        for(int i = 0; i < Main.MAX_PRODUCTS; i++){
            
            if(Main.END_LINE.equals(Main.product[i].getProductCode()) && i == 0){
                return "0001";
            }
            
            if(Main.END_LINE.equals(Main.product[i + 1].getProductCode())) {
                 
                int newNum = Integer.parseInt(Main.product[i].getProductCode().substring(4, 8)) + 1;
               
                num = newNum + "";

                if(num.length() == 1){
                    num = "000" + num;
                    return num;
                } else if (num.length() == 2){
                    num = "00" + num;
                    return num;
                } else if (num.length() == 3){
                    num = "0" + num;
                    return num;
                } else {
                    return num;
                }

            } else {
              continue;
            }
        }
        return num;
    }
        
    public boolean checkQuantity(){
       
        String quantity = productQuantity.getText();
     
        if(Integer.parseInt(quantity) <= 0){     
            System.out.print("The quantity should be greater than 0");
            return false;
        }
        return true;
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmAddButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel productCodeDisplay;
    private javax.swing.JTextField productNameText;
    private javax.swing.JFormattedTextField productQuantity;
    // End of variables declaration//GEN-END:variables
}
